### PR TITLE
Add Cap'n Proto to benchmark.

### PR DESCRIPTION
**Pull request by kentonv**
Results:

$ ./test 100000
performing 100000 iterations

thrift-binary: version = 0.9.1
thrift-binary: size = 17017 bytes
thrift-binary: time = 9253 milliseconds

thrift-compact: version = 0.9.1
thrift-compact: size = 11597 bytes
thrift-compact: time = 12249 milliseconds

protobuf: version = 2006000
protobuf: size = 12571 bytes
protobuf: time = 9349 milliseconds

capnproto: version = 5002
capnproto: size = 17768 bytes
capnproto: time = 5 milliseconds

boost: version = 105600
boost: size = 17470 bytes
boost: time = 8942 milliseconds

msgpack: version = 0.5.9
msgpack: size = 11902 bytes
msgpack: time = 6669 milliseconds

cereal: size = 17416 bytes
cereal: time = 3608 milliseconds

avro: size = 12288 bytes
avro: time = 8236 milliseconds

### CODE REVIEW

**Comment by kentonv** [comment]
(This was requested by someone on our mailing list: https://groups.google.com/d/msg/capnproto/Q3ivsQ467_o/qeJPef5lUfoJ)

**Comment by thekvs** [comment]
Compared to other serialization libs 5 milliseconds seems a bit suspicious.

**Comment by kentonv** [comment]
Hi Konstantin,

Actually, this is exactly what is expected. Cap'n Proto has O(1) serialization/parsing time whereas all of the other protocols have O(n) time. This is exactly what Cap'n Proto was designed to do. See: https://capnproto.org

That said, I'm certainly not going to argue that these numbers would be useful when choosing a protocol. In fact, I'm arguing the opposite. Unfortunately, you just can't compare the performance of multiple serialization frameworks by running the parse/serialize step on random dummy data in a loop. Cap'n Proto's numbers make this really obvious, but it applies to all the other numbers as well.

For another example, your test case is measuring a message containing a large list of random uniformly-distributed integers and a large list of identical random-content strings. For almost all serializers, the string list will boil down to a lot of memcpy(), so that part is basically measuring RAM bandwidth, thus watering down the numbers. The int list, on the other hand, is going to perform wildly differently with different serializers because of the various ways that integers are encoded.

For your particular data set, you can more than _double_ the protobuf case's performance -- with a 2% increase in message size -- by changing the declaration to:

    repeated fixed32 ids = 1 [packed = true];

But the thing is, a list of integers uniformly distributed in the range [0,65536) is just not a common data set in the wild. If you try a different data set, you'll get totally different results. By choosing the right data set, or by measuring the right subset of the overall serialization process, you can make any serialization system win or lose the benchmark.

Point is, to usefully benchmark a serialization framework you need to measure an end-to-end system that is doing real work. And even then you only really know which serialization system performs best for that particular end-to-end system.

FWIW, I'm confident that Cap'n Proto would win most (but not all) such benchmarks, though obviously not by the margin shown in this pull request.

(Disclosure: I'm the author of both Cap'n Proto and Protobuf v2.)

**Comment by joshuawarner32** [comment]
I would humbly suggest to make these tests more meaningful:
* Also measure the time to do a full round-trip of data, from writing in the values, encoding, decoding, and finally verifying the values again.  If those were measured individually, I might expect capnproto to slip down the ranks in terms of the reading & writing times, since the pointer format & default-value handling will have slightly more overhead than just writing "native" pointers.  Then again, the arena allocation could more than make up for that.
* Include another test that writes highly nested data.  I might suggest picking a random xml/json document in the wild, and "transcode" it in the most direct fashion possible.  Of course, you'd want to do that by hand, so as not to include the overhead of processing xml/json.

That certainly wouldn't apply to every case, but it might help people make more informed decisions.

**Comment by kentonv** [comment]
It would probably also make sense to write to a real socket or file rather than just building a string in memory. The introduction of system calls would probably reduce cache efficiency, hurting those serialization systems that have a larger working set. The I/O time is also likely to be proportional to the encoded message size, so would favor formats with higher compression ratio.

**Comment by thekvs** [comment]
Hi Kenton!

Thank you for your suggestions and the patch. It's true that the benchmark definitely needs to be improved to be more close to a real life scenarios. In a week or two I'll have some spare time and will try to improve it. If you have some more ideas of how it should be done please share it with me.

**Comment by kentonv** [comment]
I recommend trying to think of semi-realistic use cases that are easy to code, and then writing them as end-to-end systems.

For example, in my own benchmarks I implemented something called "Catrank". The idea is that you have a search engine where someone has done a search, a provisional set of search results has been returned by the index (with scores), and then the program's goal is to modify those scores by promoting the ones with "cat" in the snippet and demoting the ones mentioning "dog" (by multiplying their scores and then re-sorting). The benchmark generates dummy search results that randomly use the words "cat" and "dog", then runs them through the fake "Catrank" system.

https://github.com/sandstorm-io/capnproto/blob/master/c++/src/benchmark/catrank.capnp
https://github.com/sandstorm-io/capnproto/blob/master/c++/src/benchmark/capnproto-catrank.c++

Anyway, that's just one idea, but the point is, even though it's not a real use case, it's an example of something you could almost imagine someone doing in real life. :)

FWIW, feel free to take whatever you want from my benchmark suite. (I only cover Cap'n Proto and Protobuf. It would be cool to cover others as well. That said, I don't have a lot of confidence that this benchmark suite is meaningful either, since it is still made-up test cases.)

**Pull request merged**
